//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_ComentarioPost", "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcBlog.Models.Post), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcBlog.Models.Comentario), true)]

#endregion

namespace MvcBlog.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comentario> Comentarios
        {
            get
            {
                if ((_Comentarios == null))
                {
                    _Comentarios = base.CreateObjectSet<Comentario>("Comentarios");
                }
                return _Comentarios;
            }
        }
        private ObjectSet<Comentario> _Comentarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Post> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Post>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Post> _Posts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comentarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComentarios(Comentario comentario)
        {
            base.AddObject("Comentarios", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosts(Post post)
        {
            base.AddObject("Posts", post);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comentario object.
        /// </summary>
        /// <param name="idComentario">Initial value of the IdComentario property.</param>
        /// <param name="autor">Initial value of the Autor property.</param>
        /// <param name="idPost">Initial value of the IdPost property.</param>
        public static Comentario CreateComentario(global::System.Int32 idComentario, global::System.String autor, global::System.Int32 idPost)
        {
            Comentario comentario = new Comentario();
            comentario.IdComentario = idComentario;
            comentario.Autor = autor;
            comentario.IdPost = idPost;
            return comentario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdComentario
        {
            get
            {
                return _IdComentario;
            }
            set
            {
                if (_IdComentario != value)
                {
                    OnIdComentarioChanging(value);
                    ReportPropertyChanging("IdComentario");
                    _IdComentario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdComentario");
                    OnIdComentarioChanged();
                }
            }
        }
        private global::System.Int32 _IdComentario;
        partial void OnIdComentarioChanging(global::System.Int32 value);
        partial void OnIdComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Autor
        {
            get
            {
                return _Autor;
            }
            set
            {
                OnAutorChanging(value);
                ReportPropertyChanging("Autor");
                _Autor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Autor");
                OnAutorChanged();
            }
        }
        private global::System.String _Autor;
        partial void OnAutorChanging(global::System.String value);
        partial void OnAutorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contenido
        {
            get
            {
                return _Contenido;
            }
            set
            {
                OnContenidoChanging(value);
                ReportPropertyChanging("Contenido");
                _Contenido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contenido");
                OnContenidoChanged();
            }
        }
        private global::System.String _Contenido;
        partial void OnContenidoChanging(global::System.String value);
        partial void OnContenidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPost
        {
            get
            {
                return _IdPost;
            }
            set
            {
                OnIdPostChanging(value);
                ReportPropertyChanging("IdPost");
                _IdPost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPost");
                OnIdPostChanged();
            }
        }
        private global::System.Int32 _IdPost;
        partial void OnIdPostChanging(global::System.Int32 value);
        partial void OnIdPostChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_ComentarioPost", "Post")]
        public Post Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("DatabaseModel.FK_ComentarioPost", "Post").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("DatabaseModel.FK_ComentarioPost", "Post").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Post> PostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("DatabaseModel.FK_ComentarioPost", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Post>("DatabaseModel.FK_ComentarioPost", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="idPost">Initial value of the IdPost property.</param>
        /// <param name="titulo">Initial value of the Titulo property.</param>
        public static Post CreatePost(global::System.Int32 idPost, global::System.String titulo)
        {
            Post post = new Post();
            post.IdPost = idPost;
            post.Titulo = titulo;
            return post;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPost
        {
            get
            {
                return _IdPost;
            }
            set
            {
                if (_IdPost != value)
                {
                    OnIdPostChanging(value);
                    ReportPropertyChanging("IdPost");
                    _IdPost = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPost");
                    OnIdPostChanged();
                }
            }
        }
        private global::System.Int32 _IdPost;
        partial void OnIdPostChanging(global::System.Int32 value);
        partial void OnIdPostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contenido
        {
            get
            {
                return _Contenido;
            }
            set
            {
                OnContenidoChanging(value);
                ReportPropertyChanging("Contenido");
                _Contenido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contenido");
                OnContenidoChanged();
            }
        }
        private global::System.String _Contenido;
        partial void OnContenidoChanging(global::System.String value);
        partial void OnContenidoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_ComentarioPost", "Comentario")]
        public EntityCollection<Comentario> Comentarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("DatabaseModel.FK_ComentarioPost", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("DatabaseModel.FK_ComentarioPost", "Comentario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
